<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
    } 

    /*
     * Listing of admins
     */
    function index()
    {
        $data['admins'] = $this->Admin_model->get_all_admins();
        
        $data['_view'] = 'admin/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new admin
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password_admin','Password Admin','required');
		$this->form_validation->set_rules('nom_admin','Nom Admin','required');
		$this->form_validation->set_rules('login_admin','Login Admin','required');
		$this->form_validation->set_rules('email_admin','Email Admin','required');
		$this->form_validation->set_rules('state','State','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password_admin' => $this->input->post('password_admin'),
				'nom_admin' => $this->input->post('nom_admin'),
				'login_admin' => $this->input->post('login_admin'),
				'email_admin' => $this->input->post('email_admin'),
				'createAt' => $this->input->post('createAt'),
				'state' => $this->input->post('state'),
            );
            
            $admin_id = $this->Admin_model->add_admin($params);
            redirect('admin/index');
        }
        else
        {            
            $data['_view'] = 'admin/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a admin
     */
    function edit($id_admin)
    {   
        // check if the admin exists before trying to edit it
        $data['admin'] = $this->Admin_model->get_admin($id_admin);
        
        if(isset($data['admin']['id_admin']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password_admin','Password Admin','required');
			$this->form_validation->set_rules('nom_admin','Nom Admin','required');
			$this->form_validation->set_rules('login_admin','Login Admin','required');
			$this->form_validation->set_rules('email_admin','Email Admin','required');
			$this->form_validation->set_rules('state','State','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'password_admin' => $this->input->post('password_admin'),
					'nom_admin' => $this->input->post('nom_admin'),
					'login_admin' => $this->input->post('login_admin'),
					'email_admin' => $this->input->post('email_admin'),
					'createAt' => $this->input->post('createAt'),
					'state' => $this->input->post('state'),
                );

                $this->Admin_model->update_admin($id_admin,$params);            
                redirect('admin/index');
            }
            else
            {
                $data['_view'] = 'admin/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The admin you are trying to edit does not exist.');
    } 

    /*
     * Deleting admin
     */
    function remove($id_admin)
    {
        $admin = $this->Admin_model->get_admin($id_admin);

        // check if the admin exists before trying to delete it
        if(isset($admin['id_admin']))
        {
            $this->Admin_model->delete_admin($id_admin);
            redirect('admin/index');
        }
        else
            show_error('The admin you are trying to delete does not exist.');
    }
    
}
