<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categorieplace extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categorieplace_model');
    } 

    /*
     * Listing of categorieplaces
     */
    function index()
    {
        $data['categorieplaces'] = $this->Categorieplace_model->get_all_categorieplaces();
        
        $data['_view'] = 'categorieplace/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new categorieplace
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('type_place','Type Place','required');
		$this->form_validation->set_rules('prix_place','Prix Place','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'state' => $this->input->post('state'),
				'type_place' => $this->input->post('type_place'),
				'prix_place' => $this->input->post('prix_place'),
				'createAt' => $this->input->post('createAt'),
            );
            
            $categorieplace_id = $this->Categorieplace_model->add_categorieplace($params);
            redirect('categorieplace/index');
        }
        else
        {            
            $data['_view'] = 'categorieplace/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a categorieplace
     */
    function edit($id_catplace)
    {   
        // check if the categorieplace exists before trying to edit it
        $data['categorieplace'] = $this->Categorieplace_model->get_categorieplace($id_catplace);
        
        if(isset($data['categorieplace']['id_catplace']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('type_place','Type Place','required');
			$this->form_validation->set_rules('prix_place','Prix Place','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'state' => $this->input->post('state'),
					'type_place' => $this->input->post('type_place'),
					'prix_place' => $this->input->post('prix_place'),
					'createAt' => $this->input->post('createAt'),
                );

                $this->Categorieplace_model->update_categorieplace($id_catplace,$params);            
                redirect('categorieplace/index');
            }
            else
            {
                $data['_view'] = 'categorieplace/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The categorieplace you are trying to edit does not exist.');
    } 

    /*
     * Deleting categorieplace
     */
    function remove($id_catplace)
    {
        $categorieplace = $this->Categorieplace_model->get_categorieplace($id_catplace);

        // check if the categorieplace exists before trying to delete it
        if(isset($categorieplace['id_catplace']))
        {
            $this->Categorieplace_model->delete_categorieplace($id_catplace);
            redirect('categorieplace/index');
        }
        else
            show_error('The categorieplace you are trying to delete does not exist.');
    }
    
}
