<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoriefood extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categoriefood_model');
    } 

    /*
     * Listing of categoriefoods
     */
    function index()
    {
        $data['categoriefoods'] = $this->Categoriefood_model->get_all_categoriefoods();
        
        $data['_view'] = 'categoriefood/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new categoriefood
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name_catfood','Name Catfood','required');
		$this->form_validation->set_rules('type_food','Type Food','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'state' => $this->input->post('state'),
				'name_catfood' => $this->input->post('name_catfood'),
				'type_food' => $this->input->post('type_food'),
				'createAt' => $this->input->post('createAt'),
            );
            
            $categoriefood_id = $this->Categoriefood_model->add_categoriefood($params);
            redirect('categoriefood/index');
        }
        else
        {            
            $data['_view'] = 'categoriefood/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a categoriefood
     */
    function edit($id_catfood)
    {   
        // check if the categoriefood exists before trying to edit it
        $data['categoriefood'] = $this->Categoriefood_model->get_categoriefood($id_catfood);
        
        if(isset($data['categoriefood']['id_catfood']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name_catfood','Name Catfood','required');
			$this->form_validation->set_rules('type_food','Type Food','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'state' => $this->input->post('state'),
					'name_catfood' => $this->input->post('name_catfood'),
					'type_food' => $this->input->post('type_food'),
					'createAt' => $this->input->post('createAt'),
                );

                $this->Categoriefood_model->update_categoriefood($id_catfood,$params);            
                redirect('categoriefood/index');
            }
            else
            {
                $data['_view'] = 'categoriefood/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The categoriefood you are trying to edit does not exist.');
    } 

    /*
     * Deleting categoriefood
     */
    function remove($id_catfood)
    {
        $categoriefood = $this->Categoriefood_model->get_categoriefood($id_catfood);

        // check if the categoriefood exists before trying to delete it
        if(isset($categoriefood['id_catfood']))
        {
            $this->Categoriefood_model->delete_categoriefood($id_catfood);
            redirect('categoriefood/index');
        }
        else
            show_error('The categoriefood you are trying to delete does not exist.');
    }
    
}
