<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detailfood extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detailfood_model');
    } 

    /*
     * Listing of detailfoods
     */
    function index()
    {
        $data['detailfoods'] = $this->Detailfood_model->get_all_detailfoods();
        
        $data['_view'] = 'detailfood/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new detailfood
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('prix_total','Prix Total','required');
		$this->form_validation->set_rules('qte','Qte','required');
		$this->form_validation->set_rules('state','State','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_food' => $this->input->post('id_food'),
				'prix_total' => $this->input->post('prix_total'),
				'qte' => $this->input->post('qte'),
				'createAt' => $this->input->post('createAt'),
				'state' => $this->input->post('state'),
            );
            
            $detailfood_id = $this->Detailfood_model->add_detailfood($params);
            redirect('detailfood/index');
        }
        else
        {
			$this->load->model('Food_model');
			$data['all_foods'] = $this->Food_model->get_all_foods();
            
            $data['_view'] = 'detailfood/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a detailfood
     */
    function edit($id_lieu)
    {   
        // check if the detailfood exists before trying to edit it
        $data['detailfood'] = $this->Detailfood_model->get_detailfood($id_lieu);
        
        if(isset($data['detailfood']['id_lieu']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('prix_total','Prix Total','required');
			$this->form_validation->set_rules('qte','Qte','required');
			$this->form_validation->set_rules('state','State','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_food' => $this->input->post('id_food'),
					'prix_total' => $this->input->post('prix_total'),
					'qte' => $this->input->post('qte'),
					'createAt' => $this->input->post('createAt'),
					'state' => $this->input->post('state'),
                );

                $this->Detailfood_model->update_detailfood($id_lieu,$params);            
                redirect('detailfood/index');
            }
            else
            {
				$this->load->model('Food_model');
				$data['all_foods'] = $this->Food_model->get_all_foods();

                $data['_view'] = 'detailfood/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The detailfood you are trying to edit does not exist.');
    } 

    /*
     * Deleting detailfood
     */
    function remove($id_lieu)
    {
        $detailfood = $this->Detailfood_model->get_detailfood($id_lieu);

        // check if the detailfood exists before trying to delete it
        if(isset($detailfood['id_lieu']))
        {
            $this->Detailfood_model->delete_detailfood($id_lieu);
            redirect('detailfood/index');
        }
        else
            show_error('The detailfood you are trying to delete does not exist.');
    }
    
}
