<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Food extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Food_model');
    } 

    /*
     * Listing of foods
     */
    function index()
    {
        $data['foods'] = $this->Food_model->get_all_foods();
        
        $data['_view'] = 'food/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new food
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nom_food','Nom Food','required');
		$this->form_validation->set_rules('prix_food','Prix Food','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'state' => $this->input->post('state'),
				'id_catfood' => $this->input->post('id_catfood'),
				'nom_food' => $this->input->post('nom_food'),
				'prix_food' => $this->input->post('prix_food'),
				'createAt' => $this->input->post('createAt'),
            );
            
            $food_id = $this->Food_model->add_food($params);
            redirect('food/index');
        }
        else
        {			$data['all_foods'] = $this->Food_model->get_all_foods();
            
            $data['_view'] = 'food/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a food
     */
    function edit($id_food)
    {   
        // check if the food exists before trying to edit it
        $data['food'] = $this->Food_model->get_food($id_food);
        
        if(isset($data['food']['id_food']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nom_food','Nom Food','required');
			$this->form_validation->set_rules('prix_food','Prix Food','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'state' => $this->input->post('state'),
					'id_catfood' => $this->input->post('id_catfood'),
					'nom_food' => $this->input->post('nom_food'),
					'prix_food' => $this->input->post('prix_food'),
					'createAt' => $this->input->post('createAt'),
                );

                $this->Food_model->update_food($id_food,$params);            
                redirect('food/index');
            }
            else
            {				$data['all_foods'] = $this->Food_model->get_all_foods();

                $data['_view'] = 'food/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The food you are trying to edit does not exist.');
    } 

    /*
     * Deleting food
     */
    function remove($id_food)
    {
        $food = $this->Food_model->get_food($id_food);

        // check if the food exists before trying to delete it
        if(isset($food['id_food']))
        {
            $this->Food_model->delete_food($id_food);
            redirect('food/index');
        }
        else
            show_error('The food you are trying to delete does not exist.');
    }
    
}
