<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Place extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Place_model');
    } 

    /*
     * Listing of places
     */
    function index()
    {
        $data['places'] = $this->Place_model->get_all_places();
        
        $data['_view'] = 'place/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new place
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('state','State','required');
		$this->form_validation->set_rules('description_place','Description Place','required');
		$this->form_validation->set_rules('etat_place','Etat Place','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'state' => $this->input->post('state'),
				'createAt' => $this->input->post('createAt'),
				'description_place' => $this->input->post('description_place'),
				'etat_place' => $this->input->post('etat_place'),
            );
            
            $place_id = $this->Place_model->add_place($params);
            redirect('place/index');
        }
        else
        {            
            $data['_view'] = 'place/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a place
     */
    function edit($id_place)
    {   
        // check if the place exists before trying to edit it
        $data['place'] = $this->Place_model->get_place($id_place);
        
        if(isset($data['place']['id_place']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('state','State','required');
			$this->form_validation->set_rules('description_place','Description Place','required');
			$this->form_validation->set_rules('etat_place','Etat Place','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'state' => $this->input->post('state'),
					'createAt' => $this->input->post('createAt'),
					'description_place' => $this->input->post('description_place'),
					'etat_place' => $this->input->post('etat_place'),
                );

                $this->Place_model->update_place($id_place,$params);            
                redirect('place/index');
            }
            else
            {
                $data['_view'] = 'place/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The place you are trying to edit does not exist.');
    } 

    /*
     * Deleting place
     */
    function remove($id_place)
    {
        $place = $this->Place_model->get_place($id_place);

        // check if the place exists before trying to delete it
        if(isset($place['id_place']))
        {
            $this->Place_model->delete_place($id_place);
            redirect('place/index');
        }
        else
            show_error('The place you are trying to delete does not exist.');
    }
    
}
