<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sponsor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sponsor_model');
    } 

    /*
     * Listing of sponsors
     */
    function index()
    {
        $data['sponsors'] = $this->Sponsor_model->get_all_sponsors();
        
        $data['_view'] = 'sponsor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sponsor
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nom_sponsor','Nom Sponsor','required');
		$this->form_validation->set_rules('logo_sponsor','Logo Sponsor','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'state' => $this->input->post('state'),
				'nom_sponsor' => $this->input->post('nom_sponsor'),
				'logo_sponsor' => $this->input->post('logo_sponsor'),
				'createAt' => $this->input->post('createAt'),
            );
            
            $sponsor_id = $this->Sponsor_model->add_sponsor($params);
            redirect('sponsor/index');
        }
        else
        {            
            $data['_view'] = 'sponsor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sponsor
     */
    function edit($id_sponsor)
    {   
        // check if the sponsor exists before trying to edit it
        $data['sponsor'] = $this->Sponsor_model->get_sponsor($id_sponsor);
        
        if(isset($data['sponsor']['id_sponsor']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nom_sponsor','Nom Sponsor','required');
			$this->form_validation->set_rules('logo_sponsor','Logo Sponsor','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'state' => $this->input->post('state'),
					'nom_sponsor' => $this->input->post('nom_sponsor'),
					'logo_sponsor' => $this->input->post('logo_sponsor'),
					'createAt' => $this->input->post('createAt'),
                );

                $this->Sponsor_model->update_sponsor($id_sponsor,$params);            
                redirect('sponsor/index');
            }
            else
            {
                $data['_view'] = 'sponsor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sponsor you are trying to edit does not exist.');
    } 

    /*
     * Deleting sponsor
     */
    function remove($id_sponsor)
    {
        $sponsor = $this->Sponsor_model->get_sponsor($id_sponsor);

        // check if the sponsor exists before trying to delete it
        if(isset($sponsor['id_sponsor']))
        {
            $this->Sponsor_model->delete_sponsor($id_sponsor);
            redirect('sponsor/index');
        }
        else
            show_error('The sponsor you are trying to delete does not exist.');
    }
    
}
