<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoriefood_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categoriefood by id_catfood
     */
    function get_categoriefood($id_catfood)
    {
        return $this->db->get_where('categoriefoods',array('id_catfood'=>$id_catfood))->row_array();
    }
        
    /*
     * Get all categoriefoods
     */
    function get_all_categoriefoods()
    {
        $this->db->order_by('id_catfood', 'desc');
        return $this->db->get('categoriefoods')->result_array();
    }
        
    /*
     * function to add new categoriefood
     */
    function add_categoriefood($params)
    {
        $this->db->insert('categoriefoods',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categoriefood
     */
    function update_categoriefood($id_catfood,$params)
    {
        $this->db->where('id_catfood',$id_catfood);
        return $this->db->update('categoriefoods',$params);
    }
    
    /*
     * function to delete categoriefood
     */
    function delete_categoriefood($id_catfood)
    {
        return $this->db->delete('categoriefoods',array('id_catfood'=>$id_catfood));
    }
}
