<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categorieplace_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categorieplace by id_catplace
     */
    function get_categorieplace($id_catplace)
    {
        return $this->db->get_where('categorieplaces',array('id_catplace'=>$id_catplace))->row_array();
    }
        
    /*
     * Get all categorieplaces
     */
    function get_all_categorieplaces()
    {
        $this->db->order_by('id_catplace', 'desc');
        return $this->db->get('categorieplaces')->result_array();
    }
        
    /*
     * function to add new categorieplace
     */
    function add_categorieplace($params)
    {
        $this->db->insert('categorieplaces',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categorieplace
     */
    function update_categorieplace($id_catplace,$params)
    {
        $this->db->where('id_catplace',$id_catplace);
        return $this->db->update('categorieplaces',$params);
    }
    
    /*
     * function to delete categorieplace
     */
    function delete_categorieplace($id_catplace)
    {
        return $this->db->delete('categorieplaces',array('id_catplace'=>$id_catplace));
    }
}
