<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detailfood_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detailfood by id_lieu
     */
    function get_detailfood($id_lieu)
    {
        return $this->db->get_where('detailfoods',array('id_lieu'=>$id_lieu))->row_array();
    }
        
    /*
     * Get all detailfoods
     */
    function get_all_detailfoods()
    {
        $this->db->order_by('id_lieu', 'desc');
        return $this->db->get('detailfoods')->result_array();
    }
        
    /*
     * function to add new detailfood
     */
    function add_detailfood($params)
    {
        $this->db->insert('detailfoods',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detailfood
     */
    function update_detailfood($id_lieu,$params)
    {
        $this->db->where('id_lieu',$id_lieu);
        return $this->db->update('detailfoods',$params);
    }
    
    /*
     * function to delete detailfood
     */
    function delete_detailfood($id_lieu)
    {
        return $this->db->delete('detailfoods',array('id_lieu'=>$id_lieu));
    }
}
