<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event by id_event
     */
    function get_event($id_event)
    {
        return $this->db->get_where('events',array('id_event'=>$id_event))->row_array();
    }
        
    /*
     * Get all events
     */
    function get_all_events()
    {
        $this->db->order_by('id_event', 'desc');
        return $this->db->get('events')->result_array();
    }
        
    /*
     * function to add new event
     */
    function add_event($params)
    {
        $this->db->insert('events',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event
     */
    function update_event($id_event,$params)
    {
        $this->db->where('id_event',$id_event);
        return $this->db->update('events',$params);
    }
    
    /*
     * function to delete event
     */
    function delete_event($id_event)
    {
        return $this->db->delete('events',array('id_event'=>$id_event));
    }
}
