<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lieux_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lieux by id_lieu
     */
    function get_lieux($id_lieu)
    {
        return $this->db->get_where('lieux',array('id_lieu'=>$id_lieu))->row_array();
    }
        
    /*
     * Get all lieux
     */
    function get_all_lieux()
    {
        $this->db->order_by('id_lieu', 'desc');
        return $this->db->get('lieux')->result_array();
    }
        
    /*
     * function to add new lieux
     */
    function add_lieux($params)
    {
        $this->db->insert('lieux',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lieux
     */
    function update_lieux($id_lieu,$params)
    {
        $this->db->where('id_lieu',$id_lieu);
        return $this->db->update('lieux',$params);
    }
    
    /*
     * function to delete lieux
     */
    function delete_lieux($id_lieu)
    {
        return $this->db->delete('lieux',array('id_lieu'=>$id_lieu));
    }
}
