<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Paiement_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get paiement by id_paiement
     */
    function get_paiement($id_paiement)
    {
        return $this->db->get_where('paiements',array('id_paiement'=>$id_paiement))->row_array();
    }
        
    /*
     * Get all paiements
     */
    function get_all_paiements()
    {
        $this->db->order_by('id_paiement', 'desc');
        return $this->db->get('paiements')->result_array();
    }
        
    /*
     * function to add new paiement
     */
    function add_paiement($params)
    {
        $this->db->insert('paiements',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update paiement
     */
    function update_paiement($id_paiement,$params)
    {
        $this->db->where('id_paiement',$id_paiement);
        return $this->db->update('paiements',$params);
    }
    
    /*
     * function to delete paiement
     */
    function delete_paiement($id_paiement)
    {
        return $this->db->delete('paiements',array('id_paiement'=>$id_paiement));
    }
}
