<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reservation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reservation by id_reservation
     */
    function get_reservation($id_reservation)
    {
        return $this->db->get_where('reservations',array('id_reservation'=>$id_reservation))->row_array();
    }
        
    /*
     * Get all reservations
     */
    function get_all_reservations()
    {
        $this->db->order_by('id_reservation', 'desc');
        return $this->db->get('reservations')->result_array();
    }
        
    /*
     * function to add new reservation
     */
    function add_reservation($params)
    {
        $this->db->insert('reservations',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reservation
     */
    function update_reservation($id_reservation,$params)
    {
        $this->db->where('id_reservation',$id_reservation);
        return $this->db->update('reservations',$params);
    }
    
    /*
     * function to delete reservation
     */
    function delete_reservation($id_reservation)
    {
        return $this->db->delete('reservations',array('id_reservation'=>$id_reservation));
    }
}
