<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sponsor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sponsor by id_sponsor
     */
    function get_sponsor($id_sponsor)
    {
        return $this->db->get_where('sponsors',array('id_sponsor'=>$id_sponsor))->row_array();
    }
        
    /*
     * Get all sponsors
     */
    function get_all_sponsors()
    {
        $this->db->order_by('id_sponsor', 'desc');
        return $this->db->get('sponsors')->result_array();
    }
        
    /*
     * function to add new sponsor
     */
    function add_sponsor($params)
    {
        $this->db->insert('sponsors',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sponsor
     */
    function update_sponsor($id_sponsor,$params)
    {
        $this->db->where('id_sponsor',$id_sponsor);
        return $this->db->update('sponsors',$params);
    }
    
    /*
     * function to delete sponsor
     */
    function delete_sponsor($id_sponsor)
    {
        return $this->db->delete('sponsors',array('id_sponsor'=>$id_sponsor));
    }
}
